### ISSUE TITLE
Make url categories filter useful

### ISSUE THREAD

**Issue by Destras** [ginogiorgi/reactWithViteAndTailwindCSS#2]
Right now when we click on the nav filters (like `Men's clothing`) it filters the page. But when we copy the URL and past it into another tab the view will not be filtered.

## Steps to reproduce
- Filter the page by `Men's clothing`
- Copy the url and past it into another tab
- Not seeing the same view as the other tab

## Desired behaviour 
Both tabs should be show the same items (be filtered by `Men's clothing`)

**Comment by ginogiorgi** [comment]
Thanks for your advice

Reading the endpoint before filtering the categories should be enough

Working on it

**Comment by ginogiorgi** [comment]
Fixed in the last commit, thanks for your support. 

Closing the issue
